[project]
name = "nns-trajectory-cache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Valmiki Kothare", email = "valmiki.kothare.vk@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "lmdb>=2.2.0",
]

[build-system]
requires = ["uv_build>=0.11.10,<0.12.0"]
build-backend = "uv_build"
